connections:
- from: uploaded_audio
  to: bus_main
frame_size: 2048
nodes:
- id: uploaded_audio
  kind: audio_file
  params:
    channels: 2
    file_path: /Users/geddydukes/Desktop/audio_ml/Audio_routing_sim/uploads/8d61e975-2eff-4bee-8b29-641b330fab3f.mp3
    loop: true
- id: source1
  kind: audio_file
  params:
    channels: 2
    file_path: /Users/geddydukes/Desktop/audio_ml/Audio_routing_sim/uploads/eadc6c38-981d-4010-9f9a-a90a9fe9a89e.mp3
    loop: true
- id: bus_main
  kind: gain
  params:
    channels: 2
    gain_db: -3.0
sample_rate: 48000
